"""Add WorkshopSession model

Revision ID: 654cb23d35e5
Revises: c3e1169900a5
Create Date: 2026-02-26 13:50:29.064168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '654cb23d35e5'
down_revision: Union[str, None] = 'c3e1169900a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop_sessions',
    sa.Column('workshop_id', sa.Uuid(), nullable=False),
    sa.Column('session_order', sa.Integer(), nullable=True),
    sa.Column('facilitator_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('content_description', sa.Text(), nullable=True),
    sa.Column('modality', sa.Enum('in_person', 'virtual', 'hybrid', name='session_modality'), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', name='session_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['facilitator_id'], ['team_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ws_date', 'workshop_sessions', ['date'], unique=False)
    op.create_index('ix_ws_facilitator_date', 'workshop_sessions', ['facilitator_id', 'date'], unique=False)
    op.create_index('ix_ws_workshop_date', 'workshop_sessions', ['workshop_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ws_workshop_date', table_name='workshop_sessions')
    op.drop_index('ix_ws_facilitator_date', table_name='workshop_sessions')
    op.drop_index('ix_ws_date', table_name='workshop_sessions')
    op.drop_table('workshop_sessions')
    # ### end Alembic commands ###
