"""Add admin full profile fields

Revision ID: c3e1169900a5
Revises: 0006_report_jobs
Create Date: 2026-02-25 15:29:21.518472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3e1169900a5'
down_revision: Union[str, None] = '0006_report_jobs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('admins', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('admins', sa.Column('role', sa.String(length=50), server_default='admin', nullable=False))
    op.add_column('admins', sa.Column('dni', sa.String(length=50), nullable=True))
    op.add_column('admins', sa.Column('phone', sa.String(length=50), nullable=True))
    op.drop_index('ix_certificate_issues_center_id', table_name='certificate_issues')
    op.drop_index('ix_certificate_issues_issue_date', table_name='certificate_issues')
    op.drop_index('ix_certificate_issues_participant_id', table_name='certificate_issues')
    op.drop_index('ix_certificate_issues_template_id', table_name='certificate_issues')
    op.drop_index('ix_certificate_issues_workshop_id', table_name='certificate_issues')
    op.drop_index('ix_certificate_signers_template_id', table_name='certificate_signers')
    op.drop_index('ix_certificate_templates_center_id', table_name='certificate_templates')
    op.drop_index('ix_comm_recipients_communication_id', table_name='communication_recipients')
    op.drop_index('ix_comm_recipients_participant_id', table_name='communication_recipients')
    op.drop_index('ix_comm_recipients_status', table_name='communication_recipients')
    op.drop_index('ix_communications_sent_at', table_name='communications')
    op.drop_index('ix_communications_sent_by_admin_id', table_name='communications')
    op.drop_index('ix_communications_workshop_id', table_name='communications')
    op.drop_index('ix_enrollments_participant_id', table_name='enrollments')
    op.drop_index('ix_enrollments_status', table_name='enrollments')
    op.drop_index('ix_enrollments_workshop_id', table_name='enrollments')
    op.drop_index('ix_enrollments_workshop_status', table_name='enrollments')
    op.drop_index('ix_workshops_cohort_year', table_name='workshops')
    op.drop_index('ix_workshops_status', table_name='workshops')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_workshops_status', 'workshops', ['status'], unique=False)
    op.create_index('ix_workshops_cohort_year', 'workshops', ['cohort_year'], unique=False)
    op.create_index('ix_enrollments_workshop_status', 'enrollments', ['workshop_id', 'status'], unique=False)
    op.create_index('ix_enrollments_workshop_id', 'enrollments', ['workshop_id'], unique=False)
    op.create_index('ix_enrollments_status', 'enrollments', ['status'], unique=False)
    op.create_index('ix_enrollments_participant_id', 'enrollments', ['participant_id'], unique=False)
    op.create_index('ix_communications_workshop_id', 'communications', ['workshop_id'], unique=False)
    op.create_index('ix_communications_sent_by_admin_id', 'communications', ['sent_by_admin_id'], unique=False)
    op.create_index('ix_communications_sent_at', 'communications', ['sent_at'], unique=False)
    op.create_index('ix_comm_recipients_status', 'communication_recipients', ['status'], unique=False)
    op.create_index('ix_comm_recipients_participant_id', 'communication_recipients', ['participant_id'], unique=False)
    op.create_index('ix_comm_recipients_communication_id', 'communication_recipients', ['communication_id'], unique=False)
    op.create_index('ix_certificate_templates_center_id', 'certificate_templates', ['center_id'], unique=False)
    op.create_index('ix_certificate_signers_template_id', 'certificate_signers', ['template_id'], unique=False)
    op.create_index('ix_certificate_issues_workshop_id', 'certificate_issues', ['workshop_id'], unique=False)
    op.create_index('ix_certificate_issues_template_id', 'certificate_issues', ['template_id'], unique=False)
    op.create_index('ix_certificate_issues_participant_id', 'certificate_issues', ['participant_id'], unique=False)
    op.create_index('ix_certificate_issues_issue_date', 'certificate_issues', ['issue_date'], unique=False)
    op.create_index('ix_certificate_issues_center_id', 'certificate_issues', ['center_id'], unique=False)
    op.drop_column('admins', 'phone')
    op.drop_column('admins', 'dni')
    op.drop_column('admins', 'role')
    op.drop_column('admins', 'last_name')
    op.drop_column('admins', 'first_name')
    # ### end Alembic commands ###
